[package]
name = "rustysound"
version = "0.1.0"
authors = ["root"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
soloud = "0.4.0"
rocket = "0.5.0-rc.1"